// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "/Users/peetstander/Projects/omni-components/app.config";
import type { default as appConfig1 } from "/Users/peetstander/Projects/omni-components/node_modules/.pnpm/@shuriken-ui+nuxt@3.1.2_nuxt@3.11.2_postcss@8.4.38_vite@5.2.8_vue@3.4.21/node_modules/@shuriken-ui/nuxt/app.config";
import type { default as appConfig2 } from "/Users/peetstander/Projects/omni-components/node_modules/.c12/github_PartnersInBiz_omni_M9B51hibRi/app.config";
import type { default as appConfig3 } from "/Users/peetstander/Projects/omni-components/node_modules/.c12/github_PartnersInBiz_omni_qPPBrXbF0L/app.config";
import type { default as appConfig4 } from "/Users/peetstander/Projects/omni-components/node_modules/.c12/github_PartnersInBiz_omni_HtcWSpAjdW/app.config";
import type { default as appConfig5 } from "/Users/peetstander/Projects/omni-components/node_modules/.c12/github_PartnersInBiz_omni_VhAOxl0RQY/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1, typeof appConfig2, typeof appConfig3, typeof appConfig4, typeof appConfig5]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}