// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/twilio/sms': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/twilio/sms.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.11.1_@parcel+watcher@2.4.1_@types+node@20.11.30_@unocss+reset@0.58.7_floating-vue@5.2.2_unocss@0.58.7_vite@5.2.6/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}